apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-btc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-btc
  template:
    metadata:
      labels:
        app: react-btc
    spec:
      containers:
        - name: react-btc
          image: impuls666/react-btc:react-btc
          ports:
            - containerPort: 5173
          env:
            - name: PORT
              value: "5173"
---
apiVersion: v1
kind: Service
metadata:
  name: react-btc
spec:
  type: NodePort
  ports:
    - port: 5173
      targetPort: 5173
  selector:
    app: react-btc
