apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-btc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: react-btc
  template:
    metadata:
      labels:
        app: react-btc
    spec:
      containers:
        - name: react-btc
          image: impuls666/react-btc:new
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: react-btc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: react-btc
